// src/source-code/catppuccinifier-gui/src/App.jsx
import { useState, React } from "react";
import "./App.css";

//Tauri
import { open, save } from "@tauri-apps/api/dialog"
import { open as openLink } from '@tauri-apps/api/shell';
import { convertFileSrc, invoke } from '@tauri-apps/api/tauri';
import { WebviewWindow } from "@tauri-apps/api/window"

//Components
import GeneratedImageBox from "./components/GeneratedImageBox";

//Resources
import { ReactComponent as SettingsIcon } from "./assets/images/settings.svg"
import { ReactComponent as GitHubIcon } from "./assets/images/github.svg"
import { ReactComponent as CloseIcon } from "./assets/images/close.svg"
import { ReactComponent as SunflowerIcon } from "./assets/images/sunflower.svg"
import { ReactComponent as PineappleIcon } from "./assets/images/pineapple.svg"
import { ReactComponent as LotusIcon } from "./assets/images/lotus.svg"
import { ReactComponent as BranchIcon } from "./assets/images/branch.svg"
import { ReactComponent as MenuIcon } from "./assets/images/menu.svg"


function App() {

  const [theme, setTheme] = useState(localStorage.getItem("theme") !== null ? localStorage.getItem("theme") : "theme-mocha")
  const [accent, setAccent] = useState(localStorage.getItem("accent") !== null ? localStorage.getItem("accent") : "blue")
  const [noiseLevel, setNoiseLevel] = useState(4);
  const [selectedImageRawPath, setSelectedImageRawPath] = useState("");
  const [selectedImagePath, setSelectedImagePath] = useState("");
  const [showGeneratedGrids, setShowGeneratedGrids] = useState(false);
  const [generatedLatteRawPath, setGeneratedLatteRawPath] = useState("");
  const [generatedLattePath, setGeneratedLattePath] = useState("");
  const [generatedFrappeRawPath, setGeneratedFrappeRawPath] = useState("");
  const [generatedFrappePath, setGeneratedFrappePath] = useState("");
  const [generatedMacchiatoRawPath, setGeneratedMacchiatoRawPath] = useState("");
  const [generatedMacchiatoPath, setGeneratedMacchiatoPath] = useState("");
  const [generatedMochaRawPath, setGeneratedMochaRawPath] = useState("");
  const [generatedMochaPath, setGeneratedMochaPath] = useState("");
  const [generatedOledRawPath, setGeneratedOledRawPath] = useState("");
  const [generatedOledPath, setGeneratedOledPath] = useState("");
  const [generatingImages, setGeneratingImages] = useState(false)
  const [showSettings, setShowSettings] = useState(false);
  const [showSideNav, setShowSideNav] = useState(false);


  async function selectImage() {

    const selected = await open({
      multiple: false,
      filters: [{
        name: "Images",
        extensions: ["png", "webp", "jpg", "jpeg"]
      }]
    });

    if (selected !== null) {

      setSelectedImageRawPath(selected);
      setSelectedImagePath(convertFileSrc(selected));
      setGeneratedLattePath("");
      setGeneratedFrappePath("");
      setGeneratedMacchiatoPath("");
      setGeneratedMochaPath("");
      setGeneratedOledPath("");
      setShowGeneratedGrids(false);
    }
  }


  async function generateImages() {

    setGeneratedLattePath("");
    setGeneratedFrappePath("");
    setGeneratedMacchiatoPath("");
    setGeneratedMochaPath("");
    setGeneratedOledPath("");

    setGeneratingImages(true);

    setShowGeneratedGrids(true);

    await invoke("clear_temp_folder");

    await invoke("generate_image", { image_path: selectedImageRawPath, noise_level: noiseLevel.toString(), flavor: "latte" })
      .then(path => {

        setGeneratedLatteRawPath(path);
        setGeneratedLattePath(convertFileSrc(path));
      })
      .catch((error) => { console.error(error) });

    await invoke("generate_image", { image_path: selectedImageRawPath, noise_level: noiseLevel.toString(), flavor: "frappe" })
      .then(path => {

        setGeneratedFrappeRawPath(path);
        setGeneratedFrappePath(convertFileSrc(path));
      })
      .catch((error) => { console.error(error) });

    await invoke("generate_image", { image_path: selectedImageRawPath, noise_level: noiseLevel.toString(), flavor: "macchiato" })
      .then(path => {

        setGeneratedMacchiatoRawPath(path);
        setGeneratedMacchiatoPath(convertFileSrc(path));
      })
      .catch((error) => { console.error(error) });

    await invoke("generate_image", { image_path: selectedImageRawPath, noise_level: noiseLevel.toString(), flavor: "mocha" })
      .then(path => {

        setGeneratedMochaRawPath(path);
        setGeneratedMochaPath(convertFileSrc(path));
      })
      .catch((error) => { console.error(error) });

    await invoke("generate_image", { image_path: selectedImageRawPath, noise_level: noiseLevel.toString(), flavor: "oled" })
      .then(path => {

        setGeneratedOledRawPath(path);
        setGeneratedOledPath(convertFileSrc(path));
      })
      .catch((error) => { console.error(error) });

    setGeneratingImages(false);
  }

  function saveImage(flavor) {

    var fileName = "";
    invoke("get_os")
      .then((os) => {

        if (os === "windows") {
          fileName = flavor + "-noise" + noiseLevel + "-" + selectedImageRawPath.split('\\').pop();
        } else {
          fileName = flavor + "-noise" + noiseLevel + "-" + selectedImageRawPath.split('/').pop();
        }

        save({
          defaultPath: fileName,
          filters: [
            {
              name: "Images (png, jpg, jpeg, webp)",
              extensions: ["png", "webp", "jpg", "jpeg"]
            }
          ]
        }).then((savedPath) => {

          switch (flavor) {
            case "latte": {
              invoke("save_image", { image_path: generatedLatteRawPath, saved_path: savedPath })
              break;
            }
            case "frappe": {
              invoke("save_image", { image_path: generatedFrappeRawPath, saved_path: savedPath })
              break;
            }
            case "macchiato": {
              invoke("save_image", { image_path: generatedMacchiatoRawPath, saved_path: savedPath })
              break;
            }
            case "mocha": {
              invoke("save_image", { image_path: generatedMochaRawPath, saved_path: savedPath })
              break;
            }
            case "oled": {
              invoke("save_image", { image_path: generatedOledRawPath, saved_path: savedPath })
              break;
            }
          }
        })
      })
  }

  function previewImage(flavor, path) {
    const webview = new WebviewWindow('preview', {
      url: 'preview.html?path=' + path,
      title: flavor + " Preview",
    })

    webview.once('tauri://created', function () { })
    webview.once('tauri://error', function (e) {
      console.error(e);
    })
  }



  function themesSettingClasses(setting) {

    if (setting === theme) {
      return "bg-skin-base border-skin-surface1"
    } else {
      return "bg-skin-mantle border-skin-surface0"
    }
  }

  function accentSettingClasses(setting) {

    if (setting === accent) {
      return "bg-skin-base border-skin-surface1 col-span-1"
    } else {
      return "bg-skin-mantle border-skin-surface0 col-span-1"
    }
  }

  //UI

  function GenerateImageSection() {

    return (
      <div className="flex flex-col flex-grow p-4">
        <div className="p-2 bg-skin-mantle rounded-xl border border-skin-surface0">
          <div>Noise Level - {noiseLevel}</div>
          <input className={"w-full slider slider-" + accent} value={noiseLevel} onChange={e => { setNoiseLevel(e.target.value) }} type="range" max={4} min={0} ></input>
        </div>

        <div className="mt-4 bg-skin-mantle p-2 rounded-xl border border-skin-surface0">
          <button
            className="bg-skin-crust p-2 rounded-xl border border-skin-surface0 hover:enabled:rounded-full disabled:bg-skin-mantle disabled:border-skin-crust flex justify-center items-center w-full"
            onClick={() => { selectImage() }}
            disabled={generatingImages}
          >
            Select Image
          </button>


          {
            selectedImagePath != "" ?
              <div className="">
                <div className="flex justify-center mt-2 mb-2 bg-skin-crust rounded-xl p-2 border border-skin-surface0">
                  <img src={selectedImagePath} className="object-contain h-60 rounded-md"></img>
                </div>

                <button
                  className="bg-skin-crust p-2 rounded-xl border border-skin-surface0 hover:enabled:rounded-full flex justify-center items-center w-full disabled:bg-skin-mantle disabled:border-skin-crust"
                  onClick={() => { generateImages() }}
                  disabled={generatingImages}
                >
                  Generate Images
                </button>
              </div>
              : null
          }
        </div>

        <div className="flex-grow"></div>

        <div className=" flex justify-start mt-4">
          <button
            className="mr-2 flex items-center bg-skin-mantle p-2 border border-skin-surface0 rounded-xl hover:rounded-full"
            onClick={() => { setShowSettings(true) }}
          >
            <div>
              <SettingsIcon className="h-5 w-5 stroke-skin-text fill-transparent mr-1" />
            </div>
            <div>
              Settings
            </div>
          </button>

          <button
            className="mr-2 flex items-center bg-skin-mantle p-2 border border-skin-surface0 rounded-xl hover:rounded-full"
            onClick={() => { openLink("https://github.com/lighttigerXIV/catppuccinifier") }}
          >
            <div>
              <GitHubIcon className="h-5 w-5 fill-skin-text mr-1" />
            </div>
            <div>
              About
            </div>
          </button>

        </div>
      </div>
    )
  }


  return (
    <div className={" h-screen grid grid-cols-12 min-w-full w-full bg-skin-crust text-skin-text " + theme}>

      <div className=" 2xl:col-span-3 xl:col-span-3 lg:col-span-5 md:col-span-6 2xl:flex xl:flex lg:flex md:flex hidden h-screen">
        <GenerateImageSection />
      </div>


      <div className=" 2xl:hidden xl:hidden lg:hidden md:hidden md-w-60 flex p-4">
        <button className=" hover:bg-skin-surface0 p-1 rounded-full" onClick={() => { setShowSideNav(true) }}>
          <MenuIcon className="w-5 h-5 fill-skin-text"/>
        </button>
      </div>

      {
        showSideNav ?
          <div className="h-screen w-screen absolute flex flex-col 2xl:hidden xl:hidden lg:hidden md:hidden md-w-60">
            <div className="w-5/6 bg-skin-crust flex-grow flex flex-col rounded-r-2xl border-r border-t border-b border-skin-surface0 overflow-auto">
              <div className="flex justify-end mt-4 mr-4">
                <button className="hover:bg-skin-surface0 rounded-full p-1 mb-2" onClick={() => { setShowSideNav(false) }}>
                  <CloseIcon className="w-5 h-5 fill-skin-text" />
                </button>
              </div>
              <GenerateImageSection />
            </div>

          </div>
          : null
      }


      <div className="2xl:col-span-9 xl:col-span-9 lg:col-span-7 md:col-span-6  col-span-12 flex overflow-auto">
        <div className="bg-skin-base flex-grow 2xl:rounded-l-2xl xl:rounded-l-2xl lg:rounded-l-2xl md:rounded-l-2xl h-screen overflow-auto ">
          {
            showGeneratedGrids ?

              <div className=" p-3">

                <div className="grid 2xl:grid-cols-3 xl:grid-cols-3 lg:grid-cols-1 md:grid-cols-1 grid-cols-1 gap-2">
                  <div className="">
                    <GeneratedImageBox
                      flavor="latte"
                      imagePath={generatedLattePath}
                      onSaveImage={() => { saveImage("latte") }}
                      onPreviewImage={() => { previewImage("Latte", generatedLatteRawPath) }}
                      disabled={generatingImages}
                    />
                  </div>

                  <div>
                    <GeneratedImageBox
                      flavor="frappe"
                      imagePath={generatedFrappePath}
                      onSaveImage={() => { saveImage("frappe") }}
                      onPreviewImage={() => { previewImage("Frappe", generatedFrappeRawPath) }}
                      disabled={generatingImages}
                    />
                  </div>

                  <div>
                    <GeneratedImageBox
                      flavor="macchiato"
                      imagePath={generatedMacchiatoPath}
                      onSaveImage={() => { saveImage("macchiato") }}
                      onPreviewImage={() => { previewImage("Macchiato", generatedMacchiatoRawPath) }}
                      disabled={generatingImages}
                    />
                  </div>

                  <div>
                    <GeneratedImageBox
                      flavor="mocha"
                      imagePath={generatedMochaPath}
                      onSaveImage={() => { saveImage("mocha") }}
                      onPreviewImage={() => { previewImage("Mocha", generatedMochaRawPath) }}
                      disabled={generatingImages}
                    />
                  </div>

                  <div>
                    <GeneratedImageBox
                      flavor="oled"
                      imagePath={generatedOledPath}
                      onSaveImage={() => { saveImage("oled") }}
                      onPreviewImage={() => { previewImage("Oled", generatedOledRawPath) }}
                      disabled={generatingImages}
                    />
                  </div>

                </div>
              </div>
              : null

          }
        </div>
      </div>

      {
        showSettings ?
          <div className=" absolute h-screen w-screen bg-skin-base flex items-start justify-center max-h-screen overflow-auto">
            <div className="p-4 bg-skin-crust m-4 rounded-2xl">

              <div className="flex justify-end">
                <div
                  className="rounded-full hover:bg-skin-surface0 cursor-pointer"
                  onClick={() => { setShowSettings(false) }}
                >
                  <CloseIcon
                    className="w-5 h-5 fill-skin-text m-1 "

                  />
                </div>
              </div>

              <div className="text-lg">
                Theme
              </div>

              <div className="grid 2xl:grid-cols-4 xl:grid-cols-4 lg:grid-cols-4 md:grid-cols-2 grid-cols-2 gap-2">
                <div
                  className={"cursor-pointer p-2 rounded-xl flex items-center justify-center border hover:bg-skin-base " + themesSettingClasses("theme-latte")}
                  onClick={() => {
                    localStorage.setItem("theme", "theme-latte");
                    setTheme("theme-latte");
                  }}
                >
                  <SunflowerIcon className=" w-5 h-5 fill-skin-text" />
                  <div className="ml-2 truncate">
                    Latte
                  </div>
                </div>

                <div
                  className={"cursor-pointer p-2 rounded-xl flex items-center justify-center border hover:bg-skin-base " + themesSettingClasses("theme-frappe")}
                  onClick={() => {
                    localStorage.setItem("theme", "theme-frappe");
                    setTheme("theme-frappe");
                  }}
                >
                  <PineappleIcon className=" w-5 h-5 fill-skin-text" />
                  <div className="ml-2 truncate">
                    Frappe
                  </div>
                </div>

                <div
                  className={"cursor-pointer p-2 rounded-xl flex items-center justify-center border hover:bg-skin-base " + themesSettingClasses("theme-macchiato")}
                  onClick={() => {
                    localStorage.setItem("theme", "theme-macchiato");
                    setTheme("theme-macchiato");
                  }}
                >
                  <LotusIcon className=" w-5 h-5 fill-skin-text" />
                  <div className="ml-2 truncate">
                    Macchiato
                  </div>
                </div>

                <div
                  className={"cursor-pointer p-2 rounded-xl flex items-center justify-center border hover:bg-skin-base " + themesSettingClasses("theme-mocha")}
                  onClick={() => {
                    localStorage.setItem("theme", "theme-mocha");
                    setTheme("theme-mocha");
                  }}
                >
                  <BranchIcon className=" w-5 h-5 fill-skin-text" />
                  <div className="ml-2 truncate">
                    Mocha
                  </div>
                </div>
              </div>


              <div className="mt-2 text-lg">
                Accent
              </div>

              <div className="grid 2xl:grid-cols-4 xl:grid-cols-4 lg:grid-cols-4 md:grid-cols-4 grid-cols-2 gap-2" >

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("rosewater")}
                  onClick={() => {
                    localStorage.setItem("accent", "rosewater");
                    setAccent("rosewater");
                  }}
                >
                  <div className="text-skin-rosewater ">
                    Rosewater
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("flamingo")}
                  onClick={() => {
                    localStorage.setItem("accent", "flamingo");
                    setAccent("flamingo");
                  }}
                >
                  <div className="text-skin-flamingo">
                    Flamingo
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("pink")}
                  onClick={() => {
                    localStorage.setItem("accent", "pink");
                    setAccent("pink");
                  }}
                >
                  <div className="text-skin-pink">
                    Pink
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("mauve")}
                  onClick={() => {
                    localStorage.setItem("accent", "mauve");
                    setAccent("mauve");
                  }}
                >
                  <div className="text-skin-mauve">
                    Mauve
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("red")}
                  onClick={() => {
                    localStorage.setItem("accent", "red");
                    setAccent("red");
                  }}
                >
                  <div className="text-skin-red">
                    Red
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("maroon")}
                  onClick={() => {
                    localStorage.setItem("accent", "maroon");
                    setAccent("maroon");
                  }}
                >
                  <div className="text-skin-maroon">
                    Maroon
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("peach")}
                  onClick={() => {
                    localStorage.setItem("accent", "peach");
                    setAccent("peach");
                  }}
                >
                  <div className="text-skin-peach">
                    Peach
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("yellow")}
                  onClick={() => {
                    localStorage.setItem("accent", "yellow");
                    setAccent("yellow");
                  }}
                >
                  <div className="text-skin-yellow">
                    Yellow
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("green")}
                  onClick={() => {
                    localStorage.setItem("accent", "green");
                    setAccent("green");
                  }}
                >
                  <div className="text-skin-green">
                    Green
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("teal")}
                  onClick={() => {
                    localStorage.setItem("accent", "teal");
                    setAccent("teal");
                  }}
                >
                  <div className="text-skin-teal">
                    Teal
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("sky")}
                  onClick={() => {
                    localStorage.setItem("accent", "sky");
                    setAccent("sky");
                  }}
                >
                  <div className="text-skin-sky">
                    Sky
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("sapphire")}
                  onClick={() => {
                    localStorage.setItem("accent", "sapphire");
                    setAccent("sapphire");
                  }}
                >
                  <div className="text-skin-sapphire">
                    Sapphire
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("blue")}
                  onClick={() => {
                    localStorage.setItem("accent", "blue");
                    setAccent("blue");
                  }}
                >
                  <div className="text-skin-blue">
                    Blue
                  </div>
                </div>

                <div
                  className={"p-2 rounded-xl border hover:bg-skin-base cursor-pointer flex items-center justify-center " + accentSettingClasses("lavender")}
                  onClick={() => {
                    localStorage.setItem("accent", "lavender");
                    setAccent("lavender");
                  }}
                >
                  <div className="text-skin-lavender">
                    Lavender
                  </div>
                </div>
              </div>
            </div>
          </div>
          : null
      }
    </div>

  );
}

export default App;

// src/source-code/catppuccinifier-gui/src/App.vue
<script lang="ts">
import { defineComponent, ref, watch } from 'vue';
import { Themes, Accents, ConversionMethods } from "./Constants"
import GenerateImageSection from "./components/GenerateImageSection.vue"
import GeneratedImageBox from './components/GeneratedImageBox.vue';
import { open, save } from "@tauri-apps/api/dialog"
import { convertFileSrc, invoke } from '@tauri-apps/api/tauri';
import { WebviewWindow } from "@tauri-apps/api/window"
import MenuSVG from "./assets/images/menu.svg"

export default defineComponent({
  name: "App",
  components: {
    GenerateImageSection,
    GeneratedImageBox
  },
  setup() {

    const theme = ref(localStorage.getItem("theme") ?? Themes.mocha);
    const accent = ref(localStorage.getItem("accent") ?? Accents.blue);
    const tailwindTheme = ref("Theme-" + theme.value);
    const itemsAccent = ref(theme.value.toLowerCase() + "-" + accent.value.toLowerCase());
    const haldLevel = ref(8);
    const conversionMethod = ref(ConversionMethods.gaussian.codename);
    const showAdvancedConversion = ref(false);
    const gaussianEuclide = ref(ConversionMethods.gaussian.properties.euclide.default);
    const gaussianNearest = ref(ConversionMethods.gaussian.properties.nearest.default);
    const gaussianSamplingMean = ref(ConversionMethods.gaussian_sampling.properties.mean.default);
    const gaussianSamplingSTD = ref(ConversionMethods.gaussian_sampling.properties.std.default);
    const gaussianSamplingIterations = ref(ConversionMethods.gaussian_sampling.properties.iterations.default);
    const linearNearest = ref(ConversionMethods.linear.properties.nearest.default);
    const sheppardPower = ref(ConversionMethods.sheppard.properties.power.default);
    const sheppardNearest = ref(ConversionMethods.sheppard.properties.nearest.default);
    const selectedImageRawPath = ref("");
    const selectedImagePath = ref("");
    const showGeneratedGrids = ref(false);
    const generatedLatteRawPath = ref("");
    const generatedLattePath = ref("");
    const generatedFrappeRawPath = ref("");
    const generatedFrappePath = ref("");
    const generatedMacchiatoRawPath = ref("");
    const generatedMacchiatoPath = ref("");
    const generatedMochaRawPath = ref("");
    const generatedMochaPath = ref("");
    const generatedOledRawPath = ref("");
    const generatedOledPath = ref("");
    const generatingImages = ref(false)
    const showSettings = ref(false);
    const showSideNav = ref(false);

    function updateHaldLevel(v: number) { haldLevel.value = v }
    function updateConversionMethod(v: string) { conversionMethod.value = v }
    function updateShowAdvancedConversion(v: boolean) { showAdvancedConversion.value = v }
    function updateGaussianEuclide(v: number) { gaussianEuclide.value = v }
    function updateGaussianNearest(v: number) { gaussianNearest.value = v }
    function updateGaussianSamplingMean(v: number) { gaussianSamplingMean.value = v }
    function updateGaussianSamplingSTD(v: number) { gaussianSamplingSTD.value = v }
    function updateGaussianSamplingIterations(v: number) { gaussianSamplingIterations.value = v }
    function updateLinearNearest(v: number) { linearNearest.value = v }
    function updateSheppardPower(v: number) { sheppardPower.value = v }
    function updateSheppardNearest(v: number) { sheppardNearest.value = v }
    function updateShowSideNav(v: boolean) { showSideNav.value = v }


    function getThemesSettingClasses(setting: string) {

      if (setting == theme.value) {
        return "bg-skin-base border-skin-surface1"
      } else {
        return "bg-skin-mantle border-skin-surface0"
      }
    }

    function getAccentSettingClasses(setting: string) {

      if (setting == accent.value) {
        return "bg-skin-base border-skin-surface1 col-span-1"
      } else {
        return "bg-skin-mantle border-skin-surface0 col-span-1"
      }
    }

    function getRadioColor() {

      return "checked:bg-skin-" + accent.value
    }

    watch(showAdvancedConversion, () => {
      if (!showAdvancedConversion.value) {
        //Resets Advanced Values
        gaussianEuclide.value = ConversionMethods.gaussian.properties.euclide.default;
        gaussianNearest.value = ConversionMethods.gaussian.properties.nearest.default;
        gaussianSamplingMean.value = ConversionMethods.gaussian_sampling.properties.mean.default;
        gaussianSamplingSTD.value = ConversionMethods.gaussian_sampling.properties.std.default;
        gaussianSamplingIterations.value = ConversionMethods.gaussian_sampling.properties.iterations.default;
        linearNearest.value = ConversionMethods.linear.properties.nearest.default;
        sheppardPower.value = ConversionMethods.sheppard.properties.power.default;
        sheppardNearest.value = ConversionMethods.sheppard.properties.nearest.default;
      }
    })

    async function selectImage() {

      const selected = await open({
        multiple: false,
        filters: [{
          name: "Images",
          extensions: ["png", "webp", "jpg", "jpeg"]
        }]
      });

      if (selected !== null && typeof (selected) === "string") {
        selectedImageRawPath.value = selected;
        selectedImagePath.value = convertFileSrc(selected);
        generatedLattePath.value = ""
        generatedFrappePath.value = ""
        generatedMacchiatoPath.value = ""
        generatedMochaPath.value = ""
        generatedOledPath.value = ""
        showGeneratedGrids.value = false
      }
    }

    async function generateImages() {

      generatedLattePath.value = "";
      generatedFrappePath.value = "";
      generatedMacchiatoPath.value = "";
      generatedMochaPath.value = "";
      generatedOledPath.value = "";
      generatingImages.value = true;
      showGeneratedGrids.value = true

      await invoke("clear_temp_folder")
        .catch(error => {
          console.error(error);
        });

      await invoke("generate_image", {
        image_path: selectedImageRawPath.value,
        hald_level: +haldLevel.value,
        flavor: "latte",
        conversion_method: conversionMethod.value,
        gaussian_euclide: +gaussianEuclide.value,
        gaussian_nearest: +gaussianNearest.value,
        gaussian_sampling_mean: +gaussianSamplingMean.value,
        gaussian_sampling_std: +gaussianSamplingSTD.value,
        gaussian_sampling_iterations: +gaussianSamplingIterations.value,
        linear_nearest: +linearNearest.value,
        sheppard_power: +sheppardPower.value,
        sheppard_nearest: +sheppardNearest.value
      })
        .then(path => {

          generatedLatteRawPath.value = path as string;
          generatedLattePath.value = convertFileSrc(path as string);
        })
        .catch((error) => { console.error(error) });

      await invoke("generate_image", {
        image_path: selectedImageRawPath.value,
        hald_level: +haldLevel.value,
        flavor: "frappe",
        conversion_method: conversionMethod.value,
        gaussian_euclide: +gaussianEuclide.value,
        gaussian_nearest: +gaussianNearest.value,
        gaussian_sampling_mean: +gaussianSamplingMean.value,
        gaussian_sampling_std: +gaussianSamplingSTD.value,
        gaussian_sampling_iterations: +gaussianSamplingIterations.value,
        linear_nearest: +linearNearest.value,
        sheppard_power: +sheppardPower.value,
        sheppard_nearest: +sheppardNearest.value
      })
        .then(path => {

          generatedFrappeRawPath.value = path as string;
          generatedFrappePath.value = convertFileSrc(path as string);
        })
        .catch((error) => { console.error(error) });

      await invoke("generate_image", {
        image_path: selectedImageRawPath.value,
        hald_level: +haldLevel.value,
        flavor: "macchiato",
        conversion_method: conversionMethod.value,
        gaussian_euclide: +gaussianEuclide.value,
        gaussian_nearest: +gaussianNearest.value,
        gaussian_sampling_mean: +gaussianSamplingMean.value,
        gaussian_sampling_std: +gaussianSamplingSTD.value,
        gaussian_sampling_iterations: +gaussianSamplingIterations.value,
        linear_nearest: +linearNearest.value,
        sheppard_power: +sheppardPower.value,
        sheppard_nearest: +sheppardNearest.value
      })
        .then(path => {

          generatedMacchiatoRawPath.value = path as string;
          generatedMacchiatoPath.value = convertFileSrc(path as string);
        })
        .catch((error) => { console.error(error) });

      await invoke("generate_image", {
        image_path: selectedImageRawPath.value,
        hald_level: +haldLevel.value,
        flavor: "mocha",
        conversion_method: conversionMethod.value,
        gaussian_euclide: +gaussianEuclide.value,
        gaussian_nearest: +gaussianNearest.value,
        gaussian_sampling_mean: +gaussianSamplingMean.value,
        gaussian_sampling_std: +gaussianSamplingSTD.value,
        gaussian_sampling_iterations: +gaussianSamplingIterations.value,
        linear_nearest: +linearNearest.value,
        sheppard_power: +sheppardPower.value,
        sheppard_nearest: +sheppardNearest.value
      })
        .then(path => {

          generatedMochaRawPath.value = path as string;
          generatedMochaPath.value = convertFileSrc(path as string);
        })
        .catch((error) => { console.error(error) });

      await invoke("generate_image", {
        image_path: selectedImageRawPath.value,
        hald_level: +haldLevel.value,
        flavor: "oled",
        conversion_method: conversionMethod.value,
        gaussian_euclide: +gaussianEuclide.value,
        gaussian_nearest: +gaussianNearest.value,
        gaussian_sampling_mean: +gaussianSamplingMean.value,
        gaussian_sampling_std: +gaussianSamplingSTD.value,
        gaussian_sampling_iterations: +gaussianSamplingIterations.value,
        linear_nearest: +linearNearest.value,
        sheppard_power: +sheppardPower.value,
        sheppard_nearest: +sheppardNearest.value
      })
        .then(path => {

          generatedOledRawPath.value = path as string;
          generatedOledPath.value = convertFileSrc(path as string)
        })
        .catch((error) => { console.error(error) });

      generatingImages.value = false;
    }

    function saveImage(flavor: string) {
      var fileName: string = "";

      invoke("get_os")
        .then((os) => {

          if (os === "windows") {
            fileName = flavor + "-noise" + haldLevel.value + "-" + selectedImageRawPath.value.split('\\').pop();
          } else {
            fileName = flavor + "-noise" + haldLevel.value + "-" + selectedImageRawPath.value.split('/').pop();
          }

          save({
            defaultPath: fileName,
            filters: [
              {
                name: "Images (png, jpg, jpeg, webp)",
                extensions: ["png", "webp", "jpg", "jpeg"]
              }
            ]
          }).then((savedPath) => {

            switch (flavor) {
              case "latte": {
                invoke("save_image", { image_path: generatedLatteRawPath.value, saved_path: savedPath })
                break;
              }
              case "frappe": {
                invoke("save_image", { image_path: generatedFrappeRawPath.value, saved_path: savedPath })
                break;
              }
              case "macchiato": {
                invoke("save_image", { image_path: generatedMacchiatoRawPath.value, saved_path: savedPath })
                break;
              }
              case "mocha": {
                invoke("save_image", { image_path: generatedMochaRawPath.value, saved_path: savedPath })
                break;
              }
              case "oled": {
                invoke("save_image", { image_path: generatedOledRawPath.value, saved_path: savedPath })
                break;
              }
            }
          })
        })
    }

    function previewImage(flavor: string, path: string) {
      const webview = new WebviewWindow('preview', {
        url: 'preview.html?path=' + path as string,
        title: flavor as string + " Preview",
      })

      webview.once('tauri://created', function () { })
      webview.once('tauri://error', function (e) {
        console.error(e);
      })

    }


    return {
      theme, accent, tailwindTheme, itemsAccent, haldLevel, conversionMethod, showAdvancedConversion, gaussianEuclide, gaussianNearest, gaussianSamplingMean, gaussianSamplingSTD,
      gaussianSamplingIterations, linearNearest, sheppardPower, sheppardNearest, selectedImageRawPath, selectedImagePath, showGeneratedGrids,
      generatedLatteRawPath, generatedLattePath, generatedFrappeRawPath, generatedFrappePath, generatedMacchiatoRawPath, generatedMacchiatoPath,
      generatedMochaRawPath, generatedMochaPath, generatedOledRawPath, generatedOledPath, generatingImages, showSettings, showSideNav,
      getThemesSettingClasses, getAccentSettingClasses, getRadioColor, updateHaldLevel, updateConversionMethod, updateShowAdvancedConversion, updateGaussianEuclide,
      updateGaussianNearest, updateGaussianSamplingMean, updateGaussianSamplingSTD, updateGaussianSamplingIterations, updateLinearNearest,
      updateSheppardNearest, updateSheppardPower, selectImage, generateImages, updateShowSideNav, saveImage, previewImage
    }
  }
});
</script>

<template>
  <div class='h-screen grid grid-cols-12 min-w-full w-full bg-skin-crust text-skin-text'
    :class="tailwindTheme">

    <div
      class=" 2xl:col-span-3 xl:col-span-3 lg:col-span-5 md:col-span-6 2xl:flex xl:flex lg:flex md:flex  hidden h-screen max-h-screen overflow-auto">

      <GenerateImageSection :items-accent="itemsAccent" v-model:hald-level="haldLevel" @update:haldLevel="updateHaldLevel"
        v-model:conversion-method="conversionMethod" @update:conversion-method="updateConversionMethod"
        v-model:show-advanced-conversion="showAdvancedConversion"
        @update:show-advanced-conversion="updateShowAdvancedConversion" v-model:gaussian-euclide="gaussianEuclide"
        @update:gaussian-euclide="updateGaussianEuclide" v-model:gaussian-nearest="gaussianNearest"
        @update:gaussian-nearest="updateGaussianNearest" v-model:gaussian-sampling-mean="gaussianSamplingMean"
        @update:gaussian-sampling-mean="updateGaussianSamplingMean" v-model:gaussian-sampling-s-t-d="gaussianSamplingSTD"
        @update:gaussian-sampling-s-t-d="updateGaussianSamplingSTD"
        v-model:gaussian-sampling-iterations="gaussianSamplingIterations"
        @update:gaussian-sampling-iterations="updateGaussianSamplingIterations" v-model:linear-nearest="linearNearest"
        @update:linear-nearest="updateLinearNearest" v-model:sheppard-power="sheppardPower"
        @update:sheppard-power="updateSheppardPower" v-model:sheppard-nearest="sheppardNearest"
        @update:sheppard-nearest="updateSheppardNearest" :accent="accent" :generating-images="generatingImages"
        @function:select-image="selectImage" :selected-image-path="selectedImagePath"
        @function:generate-images="generateImages" />
    </div>

    <div class="2xl:hidden xl:hidden lg:hidden md:hidden md-w-60 flex p-4">

      <button class=" hover:bg-skin-surface0 p-1 rounded-full" @click="updateShowSideNav(true)">

        <MenuSVG class="w-5 h-5 fill-skin-text" />
      </button>
    </div>

    <div v-if="showSideNav"
      class="h-screen w-screen absolute flex flex-col 2xl:hidden xl:hidden lg:hidden md:hidden md-w-60">

      <div
        class="w-5/6 bg-skin-crust flex-grow flex flex-col rounded-r-2xl border-r border-t border-b border-skin-surface0 overflow-auto">

        <div class="flex justify-end mt-4 mr-4">

          <button class="hover:bg-skin-surface0 rounded-full p-1 mb-2" @click="updateShowSideNav(false)">

            <CloseSVG class="w-5 h-5 fill-skin-text" />
          </button>
        </div>
      </div>
    </div>

    <div class="2xl:col-span-9 xl:col-span-9 lg:col-span-7 md:col-span-6  col-span-12 flex overflow-auto">

      <div
        class="bg-skin-base flex-grow 2xl:rounded-l-2xl xl:rounded-l-2xl lg:rounded-l-2xl md:rounded-l-2xl h-screen overflow-auto ">

        <div v-if="showGeneratedGrids">

          <div class="p-3">

            <div class="grid 2xl:grid-cols-3 xl:grid-cols-3 lg:grid-cols-1 md:grid-cols-1 grid-cols-1 gap-2">

              <div>

                <GeneratedImageBox :items-accent="itemsAccent" :disabled="generatingImages" flavor="latte"
                  :image-path="generatedLattePath" @function:preview-image="previewImage('latte', generatedLatteRawPath)"
                  @function:save-image="saveImage('latte')" />
              </div>

              <div>

                <GeneratedImageBox :items-accent="itemsAccent" :disabled="generatingImages" flavor="frappe"
                  :image-path="generatedFrappePath"
                  @function:preview-image="previewImage('frappe', generatedLatteRawPath)"
                  @function:save-image="saveImage('frappe')" />
              </div>

              <div>

                <GeneratedImageBox :items-accent="itemsAccent" :disabled="generatingImages" flavor="macchiato"
                  :image-path="generatedMacchiatoPath"
                  @function:preview-image="previewImage('macchiato', generatedLatteRawPath)"
                  @function:save-image="saveImage('macchiato')" />
              </div>

              <div>
                <GeneratedImageBox :items-accent="itemsAccent" :disabled="generatingImages" flavor="mocha"
                  :image-path="generatedMochaPath" @function:preview-image="previewImage('mocha', generatedLatteRawPath)"
                  @function:save-image="saveImage('mocha')" />
              </div>

              <div>
                <GeneratedImageBox :items-accent="itemsAccent" :disabled="generatingImages" flavor="oled"
                  :image-path="generatedOledPath" @function:preview-image="previewImage('oled', generatedLatteRawPath)"
                  @function:save-image="saveImage('oled')" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
