// src/catppuccinifier-gui/src/App.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { Themes, Accents, ConversionMethods } from "./Constants"
import GenerateImageSection from "./components/GenerateImageSection.vue"
import GeneratedImageBox from './components/GeneratedImageBox.vue';
import { open, save } from "@tauri-apps/api/dialog"
import { convertFileSrc, invoke } from '@tauri-apps/api/tauri';
import { WebviewWindow } from "@tauri-apps/api/window"
import MenuSVG from "./assets/images/menu.svg"


const theme = ref(localStorage.getItem("theme") ?? Themes.mocha);
const accent = ref(localStorage.getItem("accent") ?? Accents.blue);
const tailwindTheme = ref("Theme-" + theme.value);
const itemsAccent = ref(theme.value.toLowerCase() + "-" + accent.value.toLowerCase());
const haldLevel = ref(8);
const conversionMethod = ref(ConversionMethods.gaussian.codename);
const showAdvancedConversion = ref(false);
const gaussianShape = ref(ConversionMethods.gaussian.properties.shape.default);
const gaussianNearest = ref(ConversionMethods.gaussian.properties.nearest.default);
const gaussianSamplingMean = ref(ConversionMethods.gaussian_sampling.properties.mean.default);
const gaussianSamplingSTD = ref(ConversionMethods.gaussian_sampling.properties.std.default);
const gaussianSamplingIterations = ref(ConversionMethods.gaussian_sampling.properties.iterations.default);
const linearNearest = ref(ConversionMethods.linear.properties.nearest.default);
const shepardPower = ref(ConversionMethods.shepard.properties.power.default);
const shepardNearest = ref(ConversionMethods.shepard.properties.nearest.default);
const selectedImageRawPath = ref("");
const selectedImagePath = ref("");
const showGeneratedGrids = ref(false);
const generatedLatteRawPath = ref("");
const generatedLattePath = ref("");
const generatedFrappeRawPath = ref("");
const generatedFrappePath = ref("");
const generatedMacchiatoRawPath = ref("");
const generatedMacchiatoPath = ref("");
const generatedMochaRawPath = ref("");
const generatedMochaPath = ref("");
const generatedOledRawPath = ref("");
const generatedOledPath = ref("");
const generatingImages = ref(false)
const showSideNav = ref(false);

function updateHaldLevel(v: number) { haldLevel.value = v }
function updateConversionMethod(v: string) { conversionMethod.value = v }
function updateShowAdvancedConversion(v: boolean) { showAdvancedConversion.value = v }
function updateGaussianShape(v: number) { gaussianShape.value = v }
function updateGaussianNearest(v: number) { gaussianNearest.value = v }
function updateGaussianSamplingMean(v: number) { gaussianSamplingMean.value = v }
function updateGaussianSamplingSTD(v: number) { gaussianSamplingSTD.value = v }
function updateGaussianSamplingIterations(v: number) { gaussianSamplingIterations.value = v }
function updateLinearNearest(v: number) { linearNearest.value = v }
function updateShepardPower(v: number) { shepardPower.value = v }
function updateShepardNearest(v: number) { shepardNearest.value = v }
function updateShowSideNav(v: boolean) { showSideNav.value = v }

watch(showAdvancedConversion, () => {
  if (!showAdvancedConversion.value) {
    //Resets Advanced Values
    gaussianShape.value = ConversionMethods.gaussian.properties.shape.default;
    gaussianNearest.value = ConversionMethods.gaussian.properties.nearest.default;
    gaussianSamplingMean.value = ConversionMethods.gaussian_sampling.properties.mean.default;
    gaussianSamplingSTD.value = ConversionMethods.gaussian_sampling.properties.std.default;
    gaussianSamplingIterations.value = ConversionMethods.gaussian_sampling.properties.iterations.default;
    linearNearest.value = ConversionMethods.linear.properties.nearest.default;
    shepardPower.value = ConversionMethods.shepard.properties.power.default;
    shepardNearest.value = ConversionMethods.shepard.properties.nearest.default;
  }
})

async function selectImage() {

  const selected = await open({
    multiple: false,
    filters: [{
      name: "Images",
      extensions: ["png", "webp", "jpg", "jpeg"]
    }]
  });

  if (selected !== null && typeof (selected) === "string") {
    selectedImageRawPath.value = selected;
    selectedImagePath.value = convertFileSrc(selected);
    generatedLattePath.value = ""
    generatedFrappePath.value = ""
    generatedMacchiatoPath.value = ""
    generatedMochaPath.value = ""
    generatedOledPath.value = ""
    showGeneratedGrids.value = false
  }
}

async function generateImages() {

  generatedLattePath.value = "";
  generatedFrappePath.value = "";
  generatedMacchiatoPath.value = "";
  generatedMochaPath.value = "";
  generatedOledPath.value = "";
  generatingImages.value = true;
  showGeneratedGrids.value = true

  await invoke("clear_temp_folder")
    .catch(error => {
      console.error(error);
    });

  await invoke("generate_image", {
    image_path: selectedImageRawPath.value,
    hald_level: +haldLevel.value,
    flavor: "latte",
    conversion_method: conversionMethod.value,
    gaussian_shape: +gaussianShape.value,
    gaussian_nearest: +gaussianNearest.value,
    gaussian_sampling_mean: +gaussianSamplingMean.value,
    gaussian_sampling_std: +gaussianSamplingSTD.value,
    gaussian_sampling_iterations: +gaussianSamplingIterations.value,
    linear_nearest: +linearNearest.value,
    shepard_power: +shepardPower.value,
    shepard_nearest: +shepardNearest.value
  })
    .then(path => {

      generatedLatteRawPath.value = path as string;
      generatedLattePath.value = convertFileSrc(path as string);
    })
    .catch((error) => { console.error(error) });

  await invoke("generate_image", {
    image_path: selectedImageRawPath.value,
    hald_level: +haldLevel.value,
    flavor: "frappe",
    conversion_method: conversionMethod.value,
    gaussian_shape: +gaussianShape.value,
    gaussian_nearest: +gaussianNearest.value,
    gaussian_sampling_mean: +gaussianSamplingMean.value,
    gaussian_sampling_std: +gaussianSamplingSTD.value,
    gaussian_sampling_iterations: +gaussianSamplingIterations.value,
    linear_nearest: +linearNearest.value,
    shepard_power: +shepardPower.value,
    shepard_nearest: +shepardNearest.value
  })
    .then(path => {

      generatedFrappeRawPath.value = path as string;
      generatedFrappePath.value = convertFileSrc(path as string);
    })
    .catch((error) => { console.error(error) });

  await invoke("generate_image", {
    image_path: selectedImageRawPath.value,
    hald_level: +haldLevel.value,
    flavor: "macchiato",
    conversion_method: conversionMethod.value,
    gaussian_shape: +gaussianShape.value,
    gaussian_nearest: +gaussianNearest.value,
    gaussian_sampling_mean: +gaussianSamplingMean.value,
    gaussian_sampling_std: +gaussianSamplingSTD.value,
    gaussian_sampling_iterations: +gaussianSamplingIterations.value,
    linear_nearest: +linearNearest.value,
    shepard_power: +shepardPower.value,
    shepard_nearest: +shepardNearest.value
  })
    .then(path => {

      generatedMacchiatoRawPath.value = path as string;
      generatedMacchiatoPath.value = convertFileSrc(path as string);
    })
    .catch((error) => { console.error(error) });

  await invoke("generate_image", {
    image_path: selectedImageRawPath.value,
    hald_level: +haldLevel.value,
    flavor: "mocha",
    conversion_method: conversionMethod.value,
    gaussian_shape: +gaussianShape.value,
    gaussian_nearest: +gaussianNearest.value,
    gaussian_sampling_mean: +gaussianSamplingMean.value,
    gaussian_sampling_std: +gaussianSamplingSTD.value,
    gaussian_sampling_iterations: +gaussianSamplingIterations.value,
    linear_nearest: +linearNearest.value,
    shepard_power: +shepardPower.value,
    shepard_nearest: +shepardNearest.value
  })
    .then(path => {

      generatedMochaRawPath.value = path as string;
      generatedMochaPath.value = convertFileSrc(path as string);
    })
    .catch((error) => { console.error(error) });

  await invoke("generate_image", {
    image_path: selectedImageRawPath.value,
    hald_level: +haldLevel.value,
    flavor: "oled",
    conversion_method: conversionMethod.value,
    gaussian_shape: +gaussianShape.value,
    gaussian_nearest: +gaussianNearest.value,
    gaussian_sampling_mean: +gaussianSamplingMean.value,
    gaussian_sampling_std: +gaussianSamplingSTD.value,
    gaussian_sampling_iterations: +gaussianSamplingIterations.value,
    linear_nearest: +linearNearest.value,
    shepard_power: +shepardPower.value,
    shepard_nearest: +shepardNearest.value
  })
    .then(path => {

      generatedOledRawPath.value = path as string;
      generatedOledPath.value = convertFileSrc(path as string)
    })
    .catch((error) => { console.error(error) });

  generatingImages.value = false;
}

function saveImage(flavor: string) {
  var fileName: string = "";

  invoke("get_os")
    .then((os) => {

      if (os === "windows") {
        fileName = flavor + "-hald" + haldLevel.value + "-" + selectedImageRawPath.value.split('\\').pop();
      } else {
        fileName = flavor + "-hald" + haldLevel.value + "-" + selectedImageRawPath.value.split('/').pop();
      }

      save({
        defaultPath: fileName,
        filters: [
          {
            name: "Images (png, jpg, jpeg, webp)",
            extensions: ["png", "webp", "jpg", "jpeg"]
          }
        ]
      }).then((savedPath) => {

        switch (flavor) {
          case "latte": {
            invoke("save_image", { image_path: generatedLatteRawPath.value, saved_path: savedPath })
            break;
          }
          case "frappe": {
            invoke("save_image", { image_path: generatedFrappeRawPath.value, saved_path: savedPath })
            break;
          }
          case "macchiato": {
            invoke("save_image", { image_path: generatedMacchiatoRawPath.value, saved_path: savedPath })
            break;
          }
          case "mocha": {
            invoke("save_image", { image_path: generatedMochaRawPath.value, saved_path: savedPath })
            break;
          }
          case "oled": {
            invoke("save_image", { image_path: generatedOledRawPath.value, saved_path: savedPath })
            break;
          }
        }
      })
    })
}

function previewImage(flavor: string, path: string) {
  const webview = new WebviewWindow('preview', {
    url: 'preview.html?path=' + path as string,
    title: flavor as string + " Preview",
  })

  webview.once('tauri://created', function () { })
  webview.once('tauri://error', function (e) {
    console.error(e);
  })

}

</script>

<template>
  <div class='h-screen grid grid-cols-12 min-w-full w-full bg-skin-crust text-skin-text' :class="tailwindTheme">

    <div
      class=" 2xl:col-span-3 xl:col-span-3 lg:col-span-5 md:col-span-6 2xl:flex xl:flex lg:flex md:flex  hidden h-screen max-h-screen overflow-auto">

      <GenerateImageSection :items-accent="itemsAccent" v-model:hald-level="haldLevel" @update:haldLevel="updateHaldLevel"
        v-model:conversion-method="conversionMethod" @update:conversion-method="updateConversionMethod"
        v-model:show-advanced-conversion="showAdvancedConversion"
        @update:show-advanced-conversion="updateShowAdvancedConversion" v-model:gaussian-shape="gaussianShape"
        @update:gaussian-shape="updateGaussianShape" v-model:gaussian-nearest="gaussianNearest"
        @update:gaussian-nearest="updateGaussianNearest" v-model:gaussian-sampling-mean="gaussianSamplingMean"
        @update:gaussian-sampling-mean="updateGaussianSamplingMean" v-model:gaussian-sampling-s-t-d="gaussianSamplingSTD"
        @update:gaussian-sampling-s-t-d="updateGaussianSamplingSTD"
        v-model:gaussian-sampling-iterations="gaussianSamplingIterations"
        @update:gaussian-sampling-iterations="updateGaussianSamplingIterations" v-model:linear-nearest="linearNearest"
        @update:linear-nearest="updateLinearNearest" v-model:shepard-power="shepardPower"
        @update:shepard-power="updateShepardPower" v-model:shepard-nearest="shepardNearest"
        @update:shepard-nearest="updateShepardNearest" :accent="accent" :generating-images="generatingImages"
        @function:select-image="selectImage" :selected-image-path="selectedImagePath"
        @function:generate-images="generateImages" />
    </div>

    <div class="2xl:hidden xl:hidden lg:hidden md:hidden md-w-60 flex p-4">

      <button class=" hover:bg-skin-surface0 p-1 rounded-full" @click="updateShowSideNav(true)">

        <MenuSVG class="w-5 h-5 fill-skin-text" />
      </button>
    </div>

    <div v-if="showSideNav"
      class="h-screen w-screen absolute flex flex-col 2xl:hidden xl:hidden lg:hidden md:hidden md-w-60">

      <div
        class="w-5/6 bg-skin-crust flex-grow flex flex-col rounded-r-2xl border-r border-t border-b border-skin-surface0 overflow-auto">

        <div class="flex justify-end mt-4 mr-4">

          <button class="hover:bg-skin-surface0 rounded-full p-1 mb-2" @click="updateShowSideNav(false)">

            <CloseSVG class="w-5 h-5 fill-skin-text" />
          </button>
        </div>
      </div>
    </div>

    <div class="2xl:col-span-9 xl:col-span-9 lg:col-span-7 md:col-span-6  col-span-12 flex overflow-auto">

      <div
        class="bg-skin-base flex-grow 2xl:rounded-l-2xl xl:rounded-l-2xl lg:rounded-l-2xl md:rounded-l-2xl h-screen overflow-auto ">

        <div v-if="showGeneratedGrids">

          <div class="p-3">

            <div class="grid 2xl:grid-cols-3 xl:grid-cols-3 lg:grid-cols-1 md:grid-cols-1 grid-cols-1 gap-2">

              <div>

                <GeneratedImageBox :items-accent="itemsAccent" :disabled="generatingImages" flavor="latte"
                  :image-path="generatedLattePath" @function:preview-image="previewImage('latte', generatedLatteRawPath)"
                  @function:save-image="saveImage('latte')" />
              </div>

              <div>

                <GeneratedImageBox :items-accent="itemsAccent" :disabled="generatingImages" flavor="frappe"
                  :image-path="generatedFrappePath"
                  @function:preview-image="previewImage('frappe', generatedLatteRawPath)"
                  @function:save-image="saveImage('frappe')" />
              </div>

              <div>

                <GeneratedImageBox :items-accent="itemsAccent" :disabled="generatingImages" flavor="macchiato"
                  :image-path="generatedMacchiatoPath"
                  @function:preview-image="previewImage('macchiato', generatedLatteRawPath)"
                  @function:save-image="saveImage('macchiato')" />
              </div>

              <div>
                <GeneratedImageBox :items-accent="itemsAccent" :disabled="generatingImages" flavor="mocha"
                  :image-path="generatedMochaPath" @function:preview-image="previewImage('mocha', generatedLatteRawPath)"
                  @function:save-image="saveImage('mocha')" />
              </div>

              <div>
                <GeneratedImageBox :items-accent="itemsAccent" :disabled="generatingImages" flavor="oled"
                  :image-path="generatedOledPath" @function:preview-image="previewImage('oled', generatedLatteRawPath)"
                  @function:save-image="saveImage('oled')" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// src/catppuccinifier-gui/src/App.jsx
import { useState, React } from "react";
import "./App.css";

//Tauri
import { open, save } from "@tauri-apps/api/dialog"
import { convertFileSrc, invoke } from '@tauri-apps/api/tauri';
import { open as openLink } from "@tauri-apps/api/shell"
import { WebviewWindow } from "@tauri-apps/api/window"

//Components
import { Slider, SvgIcon } from "@mui/material";
import GeneratedImageBox from "./components/GeneratedImageBox";


function App() {

  const [noiseLevel, setNoiseLevel] = useState(4);
  const [selectedImageRawPath, setSelectedImageRawPath] = useState("");
  const [selectedImagePath, setSelectedImagePath] = useState("");
  const [showGeneratedGrids, setShowGeneratedGrids] = useState(false);
  const [generatedLatteRawPath, setGeneratedLatteRawPath] = useState("");
  const [generatedLattePath, setGeneratedLattePath] = useState("");
  const [generatedFrappeRawPath, setGeneratedFrappeRawPath] = useState("");
  const [generatedFrappePath, setGeneratedFrappePath] = useState("");
  const [generatedMacchiatoRawPath, setGeneratedMacchiatoRawPath] = useState("");
  const [generatedMacchiatoPath, setGeneratedMacchiatoPath] = useState("");
  const [generatedMochaRawPath, setGeneratedMochaRawPath] = useState("");
  const [generatedMochaPath, setGeneratedMochaPath] = useState("");
  const [generatedOledRawPath, setGeneratedOledRawPath] = useState("");
  const [generatedOledPath, setGeneratedOledPath] = useState("");
  const [generatingImages, setGeneratingImages] = useState(false)

  

  async function selectImage() {

    const selected = await open({
      multiple: false,
      filters: [{
        name: "Images",
        extensions: ["png", "webp", "jpg", "jpeg"]
      }]
    });

    if (selected !== null) {

      setSelectedImageRawPath(selected);
      setSelectedImagePath(convertFileSrc(selected));
      setGeneratedLattePath("");
      setGeneratedFrappePath("");
      setGeneratedMacchiatoPath("");
      setGeneratedMochaPath("");
      setGeneratedOledPath("");
      setShowGeneratedGrids(false);
    }
  }


  async function generateImages() {

    setGeneratedLattePath("");
    setGeneratedFrappePath("");
    setGeneratedMacchiatoPath("");
    setGeneratedMochaPath("");
    setGeneratedOledPath("");

    setGeneratingImages(true);

    setShowGeneratedGrids(true);

    await invoke("clear_temp_folder");

    await invoke("generate_image", { image_path: selectedImageRawPath, noise_level: noiseLevel.toString(), flavor: "latte" })
      .then(path => {

        setGeneratedLatteRawPath(path);
        setGeneratedLattePath(convertFileSrc(path));
      })
      .catch((error) => { console.error(error) });

    await invoke("generate_image", { image_path: selectedImageRawPath, noise_level: noiseLevel.toString(), flavor: "frappe" })
      .then(path => {

        setGeneratedFrappeRawPath(path);
        setGeneratedFrappePath(convertFileSrc(path));
      })
      .catch((error) => { console.error(error) });

    await invoke("generate_image", { image_path: selectedImageRawPath, noise_level: noiseLevel.toString(), flavor: "macchiato" })
      .then(path => {

        setGeneratedMacchiatoRawPath(path);
        setGeneratedMacchiatoPath(convertFileSrc(path));
      })
      .catch((error) => { console.error(error) });

    await invoke("generate_image", { image_path: selectedImageRawPath, noise_level: noiseLevel.toString(), flavor: "mocha" })
      .then(path => {

        setGeneratedMochaRawPath(path);
        setGeneratedMochaPath(convertFileSrc(path));
      })
      .catch((error) => { console.error(error) });

    await invoke("generate_image", { image_path: selectedImageRawPath, noise_level: noiseLevel.toString(), flavor: "oled" })
      .then(path => {

        setGeneratedOledRawPath(path);
        setGeneratedOledPath(convertFileSrc(path));
      })
      .catch((error) => { console.error(error) });

    setGeneratingImages(false);
  }

  function saveImage(flavor) {

    const fileName = flavor + "-noise" + noiseLevel + "-" + selectedImageRawPath.split('/').pop()

    save({
      defaultPath: fileName,
      filters: [
        {
          name: "Images (png, jpg, jpeg, webp)",
          extensions: ["png", "webp", "jpg", "jpeg"]
        }
      ]
    }).then((savedPath) => {

      switch (flavor) {
        case "latte": {
          invoke("save_image", { image_path: generatedLatteRawPath, saved_path: savedPath })
          break;
        }
        case "frappe": {
          invoke("save_image", { image_path: generatedFrappeRawPath, saved_path: savedPath })
          break;
        }
        case "macchiato": {
          invoke("save_image", { image_path: generatedMacchiatoRawPath, saved_path: savedPath })
          break;
        }
        case "mocha": {
          invoke("save_image", { image_path: generatedMochaRawPath, saved_path: savedPath })
          break;
        }
        case "oled": {
          invoke("save_image", { image_path: generatedOledRawPath, saved_path: savedPath })
          break;
        }
      }
    })
  }

  function previewImage(flavor, path) {
    const webview = new WebviewWindow('preview', {
      url: 'preview.html?path=' + path,
      title: flavor + " Preview",
    })

    webview.once('tauri://created', function () { })
    webview.once('tauri://error', function (e) {
      console.error(e);
    })
  }


  return (
    <div className="grid grid-cols-12 h-full min-h-screen min-w-full w-full bg-base text-text">
      <div className="xl:col-span-3 lg:col-span-4 h-full md:col-span-5 col-span-12 bg-crust p-3 flex flex-col">
        <div className="">
          <div className="text-2xl">Properties</div>
          <div>Noise Level - {noiseLevel}</div>
          <Slider size="small" defaultValue={4} max={4} color="secondary" onChange={e => { setNoiseLevel(e.target.value) }}></Slider>



          <button
            className="bg-surface0 p-2 rounded-xl hover:enabled:rounded-full disabled:bg-surface1 flex justify-center items-center w-full"
            onClick={() => { selectImage() }}
            disabled={generatingImages}
          >
            Select Image
          </button>


          {
            selectedImagePath != "" ?
              <div>

                <div className="w-100 flex justify-center my-4 bg-surface0 p-2 rounded-lg">
                  <img src={selectedImagePath} className="object-contain h-60 rounded-md"></img>
                </div>

                <button
                  className="bg-surface0 p-2 rounded-xl hover:enabled:rounded-full flex justify-center items-center w-full disabled:bg-surface1"
                  onClick={() => { generateImages() }}
                  disabled={generatingImages}
                >
                  Generate Images
                </button>
              </div>
              : null
          }
        </div>

        <div className="flex-1 flex items-end ">
          <div className="flex items-center">
            <div
              className="mr-2 mt-2"
            >
              Follow the project on
              <b
                className="text-mauve hover:cursor-pointer ml-1"
                onClick={() => { openLink("https://github.com/lighttigerXIV/catppuccinifier") }}
              >
                GitHub
              </b>
            </div>
          </div>
        </div>
      </div>

      {
        showGeneratedGrids ?

          <div className="xl:col-span-9 lg:col-span-8 md:col-span-7 col-span-12 p-3">

            <div className="text-2xl">Generated Images</div>

            <div className="grid xl:grid-cols-3 lg:grid-cols-2 md:grid-cols-1">
              <div className="">
                <GeneratedImageBox
                  flavor="latte"
                  imagePath={generatedLattePath}
                  onSaveImage={() => { saveImage("latte") }}
                  onPreviewImage={() => { previewImage("Latte", generatedLatteRawPath) }}
                  disabled={generatingImages}
                />
              </div>

              <div>
                <GeneratedImageBox
                  flavor="frappe"
                  imagePath={generatedFrappePath}
                  onSaveImage={() => { saveImage("frappe") }}
                  onPreviewImage={() => { previewImage("Frappe", generatedFrappeRawPath) }}
                  disabled={generatingImages}
                />
              </div>

              <div>
                <GeneratedImageBox
                  flavor="macchiato"
                  imagePath={generatedMacchiatoPath}
                  onSaveImage={() => { saveImage("macchiato") }}
                  onPreviewImage={() => { previewImage("Macchiato", generatedMacchiatoRawPath) }}
                  disabled={generatingImages}
                />
              </div>

              <div>
                <GeneratedImageBox
                  flavor="mocha"
                  imagePath={generatedMochaPath}
                  onSaveImage={() => { saveImage("mocha") }}
                  onPreviewImage={() => { previewImage("Mocha", generatedMochaRawPath) }}
                  disabled={generatingImages}
                />
              </div>

              <div>
                <GeneratedImageBox
                  flavor="oled"
                  imagePath={generatedOledPath}
                  onSaveImage={() => { saveImage("oled") }}
                  onPreviewImage={() => { previewImage("Oled", generatedOledRawPath) }}
                  disabled={generatingImages}
                />
              </div>

            </div>
          </div>
          : null

      }
    </div>

  );
}

export default App;
